---
- name: Install Apache and upload index.html
  hosts: all
  become: yes

  roles:
   - { role: install_httpd, when: ansible_os_family == "RedHat" }
   - { role: install_vsftpd, when: ansible_os_family == "RedHat" }
